export const TOOLS = [
  // ── C1: INSTANT INTERACTION ──────────────────────────────────────
  {
    cat: 'c1', name: 'Zoom Polls', logo: 'Z', logoColor: '#2D8CFF',
    tag: 'داخل Zoom', tagColor: '#2D8CFF',
    desc: 'استطلاع رأي مباشر يظهر للطلاب داخل Zoom دون مغادرة اللقاء. نتائج فورية على الشاشة.',
    use: 'الافتتاحية النقدية — تصويت على قضية مجتمعية قبل النقاش',
    free: 'yes', link: 'https://zoom.us',
  },
  {
    cat: 'c1', name: 'Zoom Reactions', logo: '😊', logoColor: '#FF9500',
    tag: 'داخل Zoom', tagColor: '#2D8CFF',
    desc: 'تعبيرات وأيقونات فورية (👍🎉❤️✋) يرسلها الطلاب بنقرة واحدة دون مقاطعة المتحدث.',
    use: 'Check-in عاطفي في بداية الحصة — "كيف حالك اليوم؟ ابعث تعبيراً"',
    free: 'yes', link: 'https://zoom.us',
  },
  {
    cat: 'c1', name: 'Mentimeter', logo: 'M', logoColor: '#5B21B6',
    tag: 'مجاني جزئياً', tagColor: '#6B21A8',
    desc: 'سحابة كلمات + تصويت + ترتيب أولويات في الوقت الفعلي. النتائج تظهر على شاشتك مباشرة.',
    use: 'سؤال افتتاحي: "ما أول كلمة تخطر على بالك؟" — بناء سحابة مفاهيمية جماعية',
    free: 'partial', link: 'https://mentimeter.com',
  },
  {
    cat: 'c1', name: 'Slido', logo: 'S', logoColor: '#7AC943',
    tag: 'أسئلة حية', tagColor: '#166534',
    desc: 'منصة للأسئلة الحية والتصويت المباشر. يستطيع الطلاب رفع الأسئلة وتصويت عليها أثناء الحصة.',
    use: 'فتح باب الأسئلة الصامتة — من يخجل من السؤال بصوت عالٍ يكتبه هنا',
    free: 'partial', link: 'https://slido.com',
  },
  {
    cat: 'c1', name: 'Poll Everywhere', logo: 'PE', logoColor: '#FF6B35',
    tag: 'استطلاع متقدم', tagColor: '#B45309',
    desc: 'أداة استطلاع متكاملة تدعم أسئلة متعددة الأنواع مع تحليلات مفصّلة.',
    use: 'تقييم لحظي لمستوى الفهم بعد كل مرحلة من الحصة',
    free: 'partial', link: 'https://polleverywhere.com',
  },
  {
    cat: 'c1', name: 'AhaSlides', logo: 'A', logoColor: '#FF4081',
    tag: 'تفاعل كامل', tagColor: '#BE185D',
    desc: 'بديل مجاني لـ Mentimeter بميزات كاملة: سحابة كلمات + تصويت + أسئلة مفتوحة + Q&A.',
    use: 'جلسات العصف الذهني الرقمي مع المجموعات الكبيرة',
    free: 'yes', link: 'https://ahaslides.com',
  },

  // ── C2: COLLABORATIVE WORK ───────────────────────────────────────
  {
    cat: 'c2', name: 'Padlet', logo: 'P', logoColor: '#FF6B6B',
    tag: 'جدار رقمي', tagColor: '#BE185D',
    desc: 'جدار رقمي مرئي يجمع النصوص والصور والروابط. يبقى الأثر ظاهراً ومشتركاً للجميع.',
    use: 'جدار المبادرة الجماعية — كل مجموعة تُضيف بطاقة لمبادرتها المجتمعية',
    free: 'partial', link: 'https://padlet.com',
  },
  {
    cat: 'c2', name: 'Miro', logo: '🟡', logoColor: '#FFD02F',
    tag: 'لوح بصري', tagColor: '#B45309',
    desc: 'لوح بصري لا نهائي للخرائط الذهنية والتخطيط الاستراتيجي وورش التصميم الجماعي.',
    use: 'تصميم خارطة طريق المبادرة المجتمعية — كل طالب يُضيف عنصراً',
    free: 'partial', link: 'https://miro.com',
  },
  {
    cat: 'c2', name: 'Jamboard', logo: 'J', logoColor: '#4285F4',
    tag: 'Google', tagColor: '#1B3A6B',
    desc: 'لوح بياض رقمي من Google يدعم الكتابة واللصاقات والرسم الجماعي في الوقت الفعلي.',
    use: 'خريطة ذهنية جماعية لقيمة مجتمعية — كل طالب يُضيف فكرة بلصاقة ملوّنة',
    free: 'yes', link: 'https://jamboard.google.com',
  },
  {
    cat: 'c2', name: 'FigJam', logo: 'F', logoColor: '#A259FF',
    tag: 'تصميم', tagColor: '#6B21A8',
    desc: 'أداة Figma للتفكير البصري الجماعي — تصاميم واضحة وجميلة للمشاريع التربوية.',
    use: 'تصميم ملصق المبادرة الرقمي بشكل جماعي وتفاعلي',
    free: 'yes', link: 'https://figma.com/figjam',
  },
  {
    cat: 'c2', name: 'Google Docs', logo: 'G', logoColor: '#4285F4',
    tag: 'كتابة مشتركة', tagColor: '#1B3A6B',
    desc: 'كتابة تعاونية حية — يرى كل طالب ما يكتبه الآخرون بالوقت الفعلي.',
    use: 'كتابة البيان الصحفي للمبادرة جماعياً — كل مجموعة في مستند مشترك',
    free: 'yes', link: 'https://docs.google.com',
  },
  {
    cat: 'c2', name: 'Zoom Whiteboard', logo: 'W', logoColor: '#2D8CFF',
    tag: 'داخل Zoom', tagColor: '#2D8CFF',
    desc: 'لوح بياض داخل Zoom يدعم الرسم والكتابة والأشكال من جميع المشاركين.',
    use: 'بناء نموذج CoI بصرياً مع الطلاب في الوقت الفعلي',
    free: 'yes', link: 'https://zoom.us',
  },

  // ── C3: ASSESSMENT ───────────────────────────────────────────────
  {
    cat: 'c3', name: 'Google Forms', logo: 'GF', logoColor: '#673AB7',
    tag: 'نماذج', tagColor: '#6B21A8',
    desc: 'نماذج احترافية لجمع البيانات والتقييمات مع تحليلات تلقائية ورسوم بيانية.',
    use: 'استطلاع ما قبل اللقاء — قياس المعرفة السابقة للطلاب',
    free: 'yes', link: 'https://forms.google.com',
  },
  {
    cat: 'c3', name: 'Microsoft Forms', logo: 'MF', logoColor: '#0078D4',
    tag: 'Microsoft', tagColor: '#0078D4',
    desc: 'نماذج سهلة من Microsoft مع تحليلات فورية ودعم كامل للغة العربية.',
    use: 'نموذج التغذية الراجعة بعد كل لقاء — رأي الطلاب في الحصة',
    free: 'yes', link: 'https://forms.microsoft.com',
  },
  {
    cat: 'c3', name: 'Typeform', logo: 'T', logoColor: '#262627',
    tag: 'نماذج جميلة', tagColor: '#374151',
    desc: 'نماذج بتجربة مستخدم استثنائية — سؤال واحد في كل خطوة يرفع معدل الإجابة.',
    use: 'استطلاع تأملي في نهاية الوحدة بتجربة سلسة ومحفّزة',
    free: 'partial', link: 'https://typeform.com',
  },
  {
    cat: 'c3', name: 'Quizizz', logo: 'Q', logoColor: '#7C3AED',
    tag: 'اختبارات', tagColor: '#6B21A8',
    desc: 'اختبارات تفاعلية بأسلوب تلعيب — مسموح بالإجابة بوتيرة كل طالب.',
    use: 'تقييم فهم المفاهيم النظرية (CoI/Vygotsky) بطريقة ممتعة',
    free: 'partial', link: 'https://quizizz.com',
  },
  {
    cat: 'c3', name: 'Socrative', logo: 'S', logoColor: '#FF4F00',
    tag: 'تقييم فوري', tagColor: '#B45309',
    desc: 'تقييم فوري مع تقارير تفصيلية لكل طالب — يتيح تتبع الفهم الفردي.',
    use: 'Exit Ticket — "ما أهم شيء تعلمته؟" في نهاية كل لقاء',
    free: 'partial', link: 'https://socrative.com',
  },

  // ── C4: GAMIFICATION ─────────────────────────────────────────────
  {
    cat: 'c4', name: 'Kahoot!', logo: 'K!', logoColor: '#46178F',
    tag: 'تنافسي', tagColor: '#6B21A8',
    desc: 'مسابقة معرفية تفاعلية بموسيقى وتشويق — تُحوّل المراجعة إلى احتفال.',
    use: 'مراجعة مفاهيم الوحدة بمسابقة — من يعرف أكثر عن التربية غير المنهجية؟',
    free: 'partial', link: 'https://kahoot.com',
  },
  {
    cat: 'c4', name: 'Quizlet Live', logo: 'QL', logoColor: '#4257B2',
    tag: 'بطاقات تعلم', tagColor: '#1B3A6B',
    desc: 'بطاقات تعلم + لعبة جماعية — الطلاب يتعاونون في فرق لمطابقة المفاهيم.',
    use: 'مطابقة المصطلحات التربوية مع تعريفاتها (CoI / ZPD / Gamification)',
    free: 'partial', link: 'https://quizlet.com/live',
  },
  {
    cat: 'c4', name: 'Gimkit', logo: 'G', logoColor: '#FF6B35',
    tag: 'اقتصاد افتراضي', tagColor: '#B45309',
    desc: 'لعبة تعليمية تعتمد اقتصاداً افتراضياً — الطلاب يكسبون نقاطاً ويستثمرونها.',
    use: 'مراجعة ممتعة بنظام المكافآت — يُعزّز الدافعية الداخلية',
    free: 'partial', link: 'https://gimkit.com',
  },
  {
    cat: 'c4', name: 'Blooket', logo: 'B', logoColor: '#2563EB',
    tag: 'ألعاب متنوعة', tagColor: '#1B3A6B',
    desc: '10+ أنواع من الألعاب التعليمية بنفس مجموعة الأسئلة — تنويع لا ينتهي.',
    use: 'جلسة مراجعة نهائية قبل التقييم بأسلوب يختاره الطلاب',
    free: 'partial', link: 'https://blooket.com',
  },
  {
    cat: 'c4', name: 'Flippity', logo: 'F', logoColor: '#4285F4',
    tag: 'ألعاب من Sheets', tagColor: '#1B3A6B',
    desc: 'تحويل Google Sheets إلى ألعاب وبطاقات تعلم وأدوات تفاعلية بدون برمجة.',
    use: 'إنشاء لعبة بطاقات مخصصة لمفاهيم التربية غير المنهجية',
    free: 'yes', link: 'https://flippity.net',
  },
  {
    cat: 'c4', name: 'Genially', logo: 'Ge', logoColor: '#FF4081',
    tag: 'محتوى تفاعلي', tagColor: '#BE185D',
    desc: 'تصميم عروض وبطاقات ومسارات تعلم تفاعلية بصرية احترافية.',
    use: 'مسار تعلم تفاعلي — الطالب يختار مساره في اكتشاف مفهوم مجتمعي',
    free: 'partial', link: 'https://genially.com',
  },

  // ── C5: DOCUMENTATION & PRODUCTION ──────────────────────────────
  {
    cat: 'c5', name: 'Canva', logo: 'Ca', logoColor: '#00C4CC',
    tag: 'تصميم', tagColor: '#0F766E',
    desc: 'أداة تصميم بصري سحابية — ملصقات، إنفوجراف، شعارات، بطاقات مبادرات.',
    use: 'تصميم ملصق المبادرة المجتمعية في الغرفة الجانبية الثانية',
    free: 'partial', link: 'https://canva.com',
  },
  {
    cat: 'c5', name: 'Book Creator', logo: 'BC', logoColor: '#E74C3C',
    tag: 'كتاب رقمي', tagColor: '#BE185D',
    desc: 'إنشاء كتب رقمية تفاعلية تشمل نصاً وصوراً وفيديو وتسجيلاً صوتياً.',
    use: 'طلاب ينشئون "كتاب مبادراتنا" الرقمي كتوثيق جماعي للوحدة',
    free: 'partial', link: 'https://bookcreator.com',
  },
  {
    cat: 'c5', name: 'Loom', logo: 'Lo', logoColor: '#625DF5',
    tag: 'تسجيل فيديو', tagColor: '#6B21A8',
    desc: 'تسجيل الشاشة والوجه معاً بنقرة واحدة — لإنشاء فيديوهات تعليمية قصيرة.',
    use: 'الطلاب يُسجّلون عرض مبادراتهم (2-3 دقائق) ويشاركون الرابط',
    free: 'partial', link: 'https://loom.com',
  },
  {
    cat: 'c5', name: 'Wakelet', logo: 'Wa', logoColor: '#003F8A',
    tag: 'تنظيم المحتوى', tagColor: '#1B3A6B',
    desc: 'تجميع وتنظيم الروابط والمقالات والفيديوهات في مجموعات بصرية منظّمة.',
    use: 'تنظيم مصادر البحث عن المبادرات المجتمعية في مجموعات موضوعية',
    free: 'yes', link: 'https://wakelet.com',
  },
  {
    cat: 'c5', name: 'Flipgrid', logo: 'Fl', logoColor: '#00B140',
    tag: 'ردود مرئية', tagColor: '#15803D',
    desc: 'الطلاب يُرسلون ردوداً بالفيديو على أسئلة المربي — محادثة مرئية غير متزامنة.',
    use: 'تأمل مرئي: "سجّل 60 ثانية تشرح فيها ما تعلمته من اللقاء الأول"',
    free: 'yes', link: 'https://flipgrid.com',
  },
  {
    cat: 'c5', name: 'Adobe Express', logo: 'Ae', logoColor: '#FF0000',
    tag: 'إبداع بصري', tagColor: '#991B1B',
    desc: 'تصميم احترافي سريع — منشورات، إنفوجراف، قصص مرئية بقوالب جاهزة.',
    use: 'تصميم انفوجراف يلخّص مراحل المبادرة المجتمعية',
    free: 'partial', link: 'https://express.adobe.com',
  },

  // ── C6: AI TOOLS ──────────────────────────────────────────────────
  {
    cat: 'c6', name: 'Claude (Anthropic)', logo: 'Cl', logoColor: '#CC7722',
    tag: 'مساعد ذكي', tagColor: '#0F766E',
    desc: 'مساعد ذكاء اصطناعي متقدم للتفكير النقدي وتصميم الأنشطة وإنشاء المحتوى.',
    use: 'توليد أسئلة سقراطية مخصصة لموضوع الحصة في ثوانٍ',
    free: 'partial', link: 'https://claude.ai',
  },
  {
    cat: 'c6', name: 'ChatGPT', logo: 'GP', logoColor: '#10A37F',
    tag: 'توليد نصي', tagColor: '#0F766E',
    desc: 'توليد أنشطة، أسئلة، شرح مفاهيم، ترجمة، وتحليل نصوص تربوية.',
    use: 'توليد 10 أسئلة تأملية عن القيادة الشبابية لحصة Zoom',
    free: 'partial', link: 'https://chat.openai.com',
  },
  {
    cat: 'c6', name: 'MagicSchool AI', logo: 'MS', logoColor: '#7C3AED',
    tag: 'للمعلمين', tagColor: '#6B21A8',
    desc: 'أداة AI مخصصة للمعلمين — خطط دروس، أنشطة، رسائل أولياء، ورقائق عمل.',
    use: 'توليد خطة حصة كاملة لموضوع "القيادة المجتمعية" في 30 ثانية',
    free: 'partial', link: 'https://magicschool.ai',
  },
  {
    cat: 'c6', name: 'Diffit', logo: 'Di', logoColor: '#F59E0B',
    tag: 'تكييف المحتوى', tagColor: '#B45309',
    desc: 'تكييف أي نص أو موضوع لمستويات مختلفة تلقائياً مع أسئلة فهم.',
    use: 'تكييف نص أكاديمي عن فريري ليكون مناسباً لطلاب السنة الأولى',
    free: 'partial', link: 'https://diffit.me',
  },
  {
    cat: 'c6', name: 'Curipod', logo: 'Cu', logoColor: '#FF6B35',
    tag: 'دروس AI', tagColor: '#B45309',
    desc: 'توليد درس تفاعلي كامل (عرض + أنشطة + أسئلة) بإدخال الموضوع فقط.',
    use: 'توليد حصة تفاعلية عن "التطوع والمواطنة" بدقيقتين',
    free: 'partial', link: 'https://curipod.com',
  },
  {
    cat: 'c6', name: 'Gamma AI', logo: 'γ', logoColor: '#6366F1',
    tag: 'عروض ذكية', tagColor: '#4338CA',
    desc: 'توليد عروض تقديمية احترافية بالذكاء الاصطناعي من موضوع أو نص.',
    use: 'توليد عرض لـ "نموذج CoI" لمشاركته مع الطلاب قبل اللقاء',
    free: 'partial', link: 'https://gamma.app',
  },

  // ── C7: BEFORE SESSION ───────────────────────────────────────────
  {
    cat: 'c7', name: 'Google Classroom', logo: 'GC', logoColor: '#34A853',
    tag: 'LMS', tagColor: '#15803D',
    desc: 'بيئة تعلم متكاملة — نشر المهام، الموارد، الإعلانات، والتواصل مع الطلاب.',
    use: 'نشر مادة التحضير (فيديو + مقال) قبل 24 ساعة من اللقاء',
    free: 'yes', link: 'https://classroom.google.com',
  },
  {
    cat: 'c7', name: 'Notion', logo: 'N', logoColor: '#000000',
    tag: 'تنظيم', tagColor: '#374151',
    desc: 'مساحة عمل متكاملة — ملاحظات، قواعد بيانات، جداول، وصفحات تعاونية.',
    use: 'بناء "مساحة الوحدة الرقمية" — كل مواد اللقاءات الثلاثة في مكان واحد',
    free: 'partial', link: 'https://notion.so',
  },
  {
    cat: 'c7', name: 'Seesaw', logo: 'Se', logoColor: '#FF6B35',
    tag: 'ملف الطالب', tagColor: '#B45309',
    desc: 'منصة ملف إنجاز رقمي — الطلاب يُضيفون أعمالهم وتعليقاتهم ونشاطاتهم.',
    use: 'إنشاء ملف إنجاز رقمي لكل طالب يوثّق مشاركته عبر الوحدة',
    free: 'partial', link: 'https://web.seesaw.me',
  },
  {
    cat: 'c7', name: 'Loom (تحضيري)', logo: 'Lo', logoColor: '#625DF5',
    tag: 'فيديو تحضيري', tagColor: '#6B21A8',
    desc: 'تسجيل فيديو تحضيري يُرسله المربي قبل اللقاء — يُهيّئ الطلاب ذهنياً.',
    use: 'تسجيل "مهمة التفكير" (5 دقائق) وإرسالها قبل اللقاء الأول',
    free: 'partial', link: 'https://loom.com',
  },
  {
    cat: 'c7', name: 'Edpuzzle', logo: 'Ed', logoColor: '#F04E23',
    tag: 'فيديو تفاعلي', tagColor: '#991B1B',
    desc: 'إضافة أسئلة على أي فيديو YouTube — يُتابع المربي من شاهد وأجاب.',
    use: 'إرسال فيديو عن مبادرة شبابية مع 3 أسئلة تحضيرية قبل اللقاء',
    free: 'partial', link: 'https://edpuzzle.com',
  },
  {
    cat: 'c7', name: 'Wakelet (تحضير)', logo: 'Wa', logoColor: '#003F8A',
    tag: 'مصادر مجمّعة', tagColor: '#1B3A6B',
    desc: 'تجميع كل مصادر اللقاء (مقالات + فيديوهات + روابط) في مكان واحد للطلاب.',
    use: 'إرسال مجموعة Wakelet "مصادر اللقاء الأول" قبل الحصة بيوم',
    free: 'yes', link: 'https://wakelet.com',
  },

  // ── C8: AFTER SESSION ─────────────────────────────────────────────
  {
    cat: 'c8', name: 'Padlet (تأملي)', logo: 'P', logoColor: '#FF6B6B',
    tag: 'تأمل ختامي', tagColor: '#BE185D',
    desc: 'جدار التأمل — الطلاب يُضيفون جملة ختامية بعد كل لقاء.',
    use: '"التعلم عن بُعد في التربية غير المنهجية هو..." — جدار ختامي مشترك',
    free: 'partial', link: 'https://padlet.com',
  },
  {
    cat: 'c8', name: 'Flipgrid (متابعة)', logo: 'Fl', logoColor: '#00B140',
    tag: 'متابعة مرئية', tagColor: '#15803D',
    desc: 'ردود مرئية غير متزامنة — الطلاب يُسجّلون تأملاتهم بعد اللقاء.',
    use: 'سجّل 90 ثانية تُجيب فيها: "ما أكثر لحظة أثّرت فيك اليوم؟"',
    free: 'yes', link: 'https://flipgrid.com',
  },
  {
    cat: 'c8', name: 'Google Forms (تقييم)', logo: 'GF', logoColor: '#673AB7',
    tag: 'تغذية راجعة', tagColor: '#6B21A8',
    desc: 'نموذج تغذية راجعة منظّم يُرسل للطلاب بعد كل لقاء.',
    use: '5 أسئلة قصيرة: ماذا تعلمت؟ ماذا أربكك؟ ماذا تريد أن تعرف أكثر؟',
    free: 'yes', link: 'https://forms.google.com',
  },
  {
    cat: 'c8', name: 'Loom (تلخيص)', logo: 'Lo', logoColor: '#625DF5',
    tag: 'ملخص مرئي', tagColor: '#6B21A8',
    desc: 'المربي يُسجّل ملخصاً لـ 2-3 دقائق يُرسله للطلاب بعد اللقاء.',
    use: 'ملخص بصري لأبرز ما نوقش واللقاء القادم — يُعزز التعلم المستمر',
    free: 'partial', link: 'https://loom.com',
  },
  {
    cat: 'c8', name: 'Notion (توثيق)', logo: 'N', logoColor: '#000000',
    tag: 'أرشيف الوحدة', tagColor: '#374151',
    desc: 'توثيق كل لقاء (ملاحظات + منتجات + قرارات) في أرشيف رقمي منظّم.',
    use: 'بناء "أرشيف الوحدة الرقمية" — كل ما أنتجناه في مكان واحد',
    free: 'partial', link: 'https://notion.so',
  },
]
